### ISSUE TITLE
RTL8710 arduino

### ISSUE THREAD

**Issue by ITstreet1** [Ameba8195/Arduino#19]
I have successfully uploaded a sketch to an RTL8720D. The goal is to use LG RX/TX with a serial adapter. My question is, do I use the same approach with RTL8710? RTL00 module.
If so, are the LOG pins in the same places? GE1 and GE0?

**Comment by kissste** [comment]
I don't think so. The firmware, in ROM, on RTL8710 does not support it.

**Comment by ITstreet1** [comment]
So, how to upload a sketch through an Arduino IDE? Is it possible to use external UART? The way I use with RTL8720?

**Comment by kissste** [comment]
My understanding is that RTL8710 supports only using SWD as a method for uploading a sketch. The firmware stored in RTL8710's ROM does NOT allow you to use Serial port (z-modem, y-modem) as a method for uploading a sketch.

Once you upload your sketch using SWD, going forward, you could program it -  in your sketch-code - to use serial or OTA going forward, but the first/ initial sketch must be uploaded using SWD, as RTL8710's firmware, stored in it's ROM simply does not support any other method, but SWD.

**Comment by ITstreet1** [comment]
Oh, I see.
So, step one should be:
- SWD adapter to upload sketch nr.1 (any sketch, blink or so...)

Step two should be:
- to use a Serial adapter and move one.

Questions:
1. What SWD adapter? ST-Link? Which one?
2. Which software? There is no option to use a Programmer with this package here in Arduino IDE.
3. How to wire a Serial adapter? What pins?

**Comment by kissste** [comment]
I would not call it "any sketch" - it needs to be your sketch that is going to implement your a method/ implementation of receiving a code from serial port, flashing it and upon reboot running it. Defacto your own bootloader

Otherwise you are correct.

**Comment by ITstreet1** [comment]
Wait a minute...
Here is a support for the RTL8710, which is not support at all. I missed something...

To upload a "bootloader" sketch I need to choose the SWD option in Arduino IDE.
-There is no option for the SWD
-I have not the slightest idea what kind of that sketch should be. Here, there is not a single line that explains it. Not to mention that "bootloader" sketch as an example.

Making support for an MCU without these parts is not support at all. Did any make this work? I haven't found not a single line someone made this work. 

When you make support for an MCU, it should have a complete package. Otherwise, it is incomplete.

**Comment by kissste** [comment]
I agree, 100%, don't waste your time on this chip. Stick with ESP8266 or ESP32.

**Comment by ITstreet1** [comment]
Then, what are the repos at your GitHub for?

**Comment by kissste** [comment]
I played with it back in ~2017 or so, had high hopes, good hardware, but no support from the vendor, and too many dead ends, resulted no adoption (in the hobby segment)
